// automatically generated by the FlatBuffers compiler, do not modify

package com.itlijunjie.pt.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatBuffersResult extends Table {
  public static FlatBuffersResult getRootAsFlatBuffersResult(ByteBuffer _bb) { return getRootAsFlatBuffersResult(_bb, new FlatBuffersResult()); }
  public static FlatBuffersResult getRootAsFlatBuffersResult(ByteBuffer _bb, FlatBuffersResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FlatBuffersResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String res() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createFlatBuffersResult(FlatBufferBuilder builder,
      int resOffset) {
    builder.startObject(1);
    FlatBuffersResult.addRes(builder, resOffset);
    return FlatBuffersResult.endFlatBuffersResult(builder);
  }

  public static void startFlatBuffersResult(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRes(FlatBufferBuilder builder, int resOffset) { builder.addOffset(0, resOffset, 0); }
  public static int endFlatBuffersResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFlatBuffersResultBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

